[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/au-programme/les-ateliers/ecriture/index.html"
to = "/au-programme/ateliers/ecriture/"

[[redirects]]
from = "/et-apres/poursuite-detudes/communication-1/index.html"
to = "/et-apres/poursuite-detudes/journalisme/"

[[redirects]]
from = "/qui-sommes-nous/promo2024/index.html"
to = "/qui-sommes-nous/promo/de-la-communication-territoriale-au-journalisme-culturel/"

[[redirects]]
from = "/au-programme/les-ateliers/pao/index.html"
to = "/au-programme/ateliers/pao/"

[[redirects]]
from = "/au-programme/le-magazine/index.html"
to = "/au-programme/magazine/"

[[redirects]]
from = "/qui-sommes-nous/promo/louis-de-la-communication-territoriale-au-journalisme-culturel/index.html"
to = "/qui-sommes-nous/promo/de-la-communication-territoriale-au-journalisme-culturel/"

[[redirects]]
from = "/au-programme/les-ateliers/com-evenementielle/index.html"
to = "/au-programme/ateliers/com-evenementielle/"

[[redirects]]
from = "/qui-sommes-nous/la-promo/index.html"
to = "/qui-sommes-nous/promo/"

[[redirects]]
from = "/boite-a-outils/lalternance/index.html"
to = "/boite-a-outils/alternance/"

[[redirects]]
from = "/promos/index.html"
to = "/qui-sommes-nous/"

[[redirects]]
from = "/au-programme/les-ateliers/com-licence/index.html"
to = "/au-programme/ateliers/com-licence/"

[[redirects]]
from = "/organisations/index.html"
to = "/boite-a-outils/organisations/"

[[redirects]]
from = "/qui-sommes-nous/la-promo/lacommunicationinterne/index.html"
to = "/qui-sommes-nous/promo/"

[[redirects]]
from = "/au-programme/les-ateliers/index.html"
to = "/au-programme/ateliers/"

[[redirects]]
from = "/qui-sommes-nous/les-anciens/index.html"
to = "/qui-sommes-nous/anciens-eleves/"

